- platform: google_keep
  name: Google Notizen Lars
  username: !secret google_keep.username
  password: !secret google_keep.password
  labels:
    - Home Assistant
- platform: steam_online
  api_key: !secret sensor_steam_api_key
  accounts: !secret sensor_steam_accounts
- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"
    - "date_time_utc"
    - "date_time_iso"
    - "time_date"
    - "time_utc"
    - "beat"
- platform: fritzbox_netmonitor
  host: !secret sensor_fritzbox_host
  name: !secret sensor_fritzbox_name
- platform: imap
  server: !secret sensor_imap_server
  port: !secret sensor_imap_port
  username: !secret sensor_imap_username
  password: !secret sensor_imap_password
  #search: FROM <sender@email.com>, SUBJECT <subject here>
  # Or use X-GM-RAW search-term like this, to find unread emails from the last 7 days in your inbox
  search: 'X-GM-RAW "in: inbox newer_than:7d is:unread"'
- platform: template
  sensors:
    date_time_now:
      friendly_name: "Datum & Uhrzeit"
      icon_template: mdi:calendar-clock
      value_template: >
        {{ as_timestamp(states('sensor.date_time_iso')) | timestamp_custom('%H:%M %d.%m.%Y %a, %b')}}
    fritzbox_online:
      friendly_name: "Online"
      value_template: "{% if is_state_attr('sensor.fritz_box_7590', 'is_connected', True) -%}Online{%- else -%}Offline{%- endif %}"
    fritzbox_max_mbit_rate_up:
      friendly_name: "Max Upload Speed"
      value_template: "{{(state_attr('sensor.fritz_box_7590', 'max_byte_rate_up') / 125000) | round(2)}}"
      unit_of_measurement: "Mbit/s"
    fritzbox_max_mbit_rate_down:
      friendly_name: "Max Download Speed"
      value_template: "{{(state_attr('sensor.fritz_box_7590', 'max_byte_rate_down') / 125000) | round(2)}}"
      unit_of_measurement: "Mbit/s"
    fritzbox_actual_mbit_rate_up:
      friendly_name: "Aktueller Upload Speed"
      value_template: "{{(state_attr('sensor.fritz_box_7590', 'transmission_rate_up') / 125000) | round(2)}}"
      unit_of_measurement: "Mbit/s"
    fritzbox_actual_mbit_rate_down:
      friendly_name: "Aktueller Download Speed"
      value_template: "{{(state_attr('sensor.fritz_box_7590', 'transmission_rate_down') / 125000) | round(2)}}"
      unit_of_measurement: "Mbit/s"
    fritzbox_uptime:
      friendly_name: "Online Zeit"
      value_template: "{{timedelta(seconds = state_attr('sensor.fritz_box_7590', 'uptime'))}}"
    fritzbox_uptime_date:
      friendly_name: "Online Seit"
      value_template: "{{as_timestamp(now() - timedelta(seconds = state_attr('sensor.fritz_box_7590', 'uptime'))) | timestamp_custom('%d.%m.%Y %H:%M ')}}"
    ink_black:
      friendly_name: "Schwarze Tinte"
      unit_of_measurement: "%"
      value_template: >
        {{ states.sensor.mfc_j5330dw_black_ink_remaining.state if states.sensor.mfc_j5330dw_black_ink_remaining.state != "unavailable" else states.input_number.schwarze_tinte.state}}
    ink_cyan:
      friendly_name: "Cyan Tinte"
      unit_of_measurement: "%"
      value_template: >
        {{ states.sensor.mfc_j5330dw_cyan_ink_remaining.state if states.sensor.mfc_j5330dw_cyan_ink_remaining.state != "unavailable" else states.input_number.cyan_tinte.state}}
    ink_magenta:
      friendly_name: "Magenta Tinte"
      unit_of_measurement: "%"
      value_template: >
        {{ states.sensor.mfc_j5330dw_magenta_ink_remaining.state if states.sensor.mfc_j5330dw_magenta_ink_remaining.state != "unavailable" else states.input_number.magenta_tinte.state}}
    ink_yellow:
      friendly_name: "Gelbe Tinte"
      unit_of_measurement: "%"
      value_template: >
        {{ states.sensor.mfc_j5330dw_yellow_ink_remaining.state if states.sensor.mfc_j5330dw_yellow_ink_remaining.state != "unavailable" else states.input_number.gelbe_tinte.state}}
    lily_cleaned_today:
      friendly_name: "Hat Lily heute gereinigt"
      value_template: >
        {{state_attr('vacuum.lily', 'clean_start').date() == now().date()}}
